version: '3.5'

networks:
  localdev:
    name: localdev

services:
    main-api:
        build: TaskTrackerApi/
        restart: always
        ports:
            - "7000:80"
        depends_on:
            - db-server
            - redis
        networks:
            - localdev
    db-server:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: db_server
        ports:
            - "1400:1433"
        environment:
            SA_PASSWORD: "SuperDuperPassword123456!"
            ACCEPT_EULA: "Y"
        networks:
            - localdev
    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - localdev
  